name: flutterbloclog
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  user_repository: 
    path: packages/user_repository
  meta: ^1.9.1
  flutter_profile_picture: ^2.0.0
  firebase_storage: ^11.2.8
  file_picker: ^6.0.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  swipe_cards: ^2.0.0+1
  image_cropper: ^5.0.0
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  http: ^1.1.0
  image_picker: ^1.0.4
  mime: ^1.0.4
  intl: ^0.18.1
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/